package progress

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/WhoisMonesh/K8S-Lab-Everything/internal/labs"
)

func ExportMarkdown() string {
	p := Load()
	p.mu.RLock()
	defer p.mu.RUnlock()

	total := len(p.Labs)
	if total == 0 {
		return "# K8S-Lab-Everything Progress Report\n\nNo labs completed yet.\n"
	}

	var totalDuration time.Duration
	byCert := make(map[string][]*LabResult)
	byDifficulty := make(map[string]int)

	for _, r := range p.Labs {
		totalDuration += r.Duration
		cert := getCertForLab(r.LabID)
		byCert[cert] = append(byCert[cert], r)
		byDifficulty[r.Difficulty]++
	}

	var b strings.Builder

	b.WriteString("# K8S-Lab-Everything Progress Report\n\n")
	b.WriteString(fmt.Sprintf("**Generated:** %s\n\n", time.Now().Format("January 2, 2006 3:04 PM")))
	b.WriteString("---\n\n")

	b.WriteString("## Summary\n\n")
	b.WriteString(fmt.Sprintf("| Metric | Value |\n"))
	b.WriteString(fmt.Sprintf("|--------|-------|\n"))
	b.WriteString(fmt.Sprintf("| Total Labs Completed | %d |\n", total))
	b.WriteString(fmt.Sprintf("| Total Practice Time | %s |\n", totalDuration.Round(time.Second)))
	b.WriteString(fmt.Sprintf("| Easy Labs | %d |\n", byDifficulty["easy"]))
	b.WriteString(fmt.Sprintf("| Medium Labs | %d |\n", byDifficulty["medium"]))
	b.WriteString(fmt.Sprintf("| Hard Labs | %d |\n", byDifficulty["hard"]))
	b.WriteString("\n")

	certOrder := []string{"CKA", "CKAD", "CKS"}
	for _, cert := range certOrder {
		labsList, ok := byCert[cert]
		if !ok || len(labsList) == 0 {
			continue
		}

		b.WriteString(fmt.Sprintf("## %s Labs (%d completed)\n\n", cert, len(labsList)))
		b.WriteString("| # | Lab ID | Title | Difficulty | Completed |\n")
		b.WriteString("|---|--------|-------|------------|----------|\n")

		sort.Slice(labsList, func(i, j int) bool {
			return labsList[i].CompletedAt.Before(labsList[j].CompletedAt)
		})

		for i, r := range labsList {
			b.WriteString(fmt.Sprintf("| %d | `%s` | %s | %s | %s |\n",
				i+1, r.LabID, r.Title, r.Difficulty,
				r.CompletedAt.Format("Jan 2, 3:04 PM")))
		}
		b.WriteString("\n")
	}

	b.WriteString("---\n\n")
	b.WriteString("*Generated by [K8S-Lab-Everything](https://github.com/WhoisMonesh/K8S-Lab-Everything)*\n")

	return b.String()
}

func ExportCertificate() string {
	p := Load()
	p.mu.RLock()
	defer p.mu.RUnlock()

	total := len(p.Labs)
	if total == 0 {
		return "# No Certificate Available\n\nComplete at least one lab to earn a certificate.\n"
	}

	ckaCount, ckadCount, cksCount := 0, 0, 0
	for _, r := range p.Labs {
		cert := getCertForLab(r.LabID)
		switch cert {
		case "CKA":
			ckaCount++
		case "CKAD":
			ckadCount++
		case "CKS":
			cksCount++
		}
	}

	var b strings.Builder

	b.WriteString("```\n")
	b.WriteString("╔══════════════════════════════════════════════════════════════════╗\n")
	b.WriteString("║                                                                  ║\n")
	b.WriteString("║                    CERTIFICATE OF COMPLETION                     ║\n")
	b.WriteString("║                                                                  ║\n")
	b.WriteString("║                     K8S-Lab-Everything                           ║\n")
	b.WriteString("║                                                                  ║\n")
	b.WriteString("╠══════════════════════════════════════════════════════════════════╣\n")
	b.WriteString("║                                                                  ║\n")
	b.WriteString(fmt.Sprintf("║  Labs Completed:  %-46d║\n", total))
	if ckaCount > 0 {
		b.WriteString(fmt.Sprintf("║  CKA Labs:        %-46d║\n", ckaCount))
	}
	if ckadCount > 0 {
		b.WriteString(fmt.Sprintf("║  CKAD Labs:       %-46d║\n", ckadCount))
	}
	if cksCount > 0 {
		b.WriteString(fmt.Sprintf("║  CKS Labs:        %-46d║\n", cksCount))
	}
	b.WriteString(fmt.Sprintf("║  Date:            %-46s║\n", time.Now().Format("January 2, 2006")))
	b.WriteString("║                                                                  ║\n")
	b.WriteString("║  Issued by: K8S-Lab-Everything                                   ║\n")
	b.WriteString("║  https://github.com/WhoisMonesh/K8S-Lab-Everything               ║\n")
	b.WriteString("║                                                                  ║\n")
	b.WriteString("╚══════════════════════════════════════════════════════════════════╝\n")
	b.WriteString("```\n")

	return b.String()
}

func getCertForLab(labID string) string {
	allLabs := labs.List()
	for _, l := range allLabs {
		if l.ID() == labID {
			return string(labs.GetCert(l))
		}
	}
	return ""
}
